name: FTP - Deploy FRONTEND

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - deploy_fe

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.client_payload.env }}
    env:
      DEPLOY_ENV: ${{ github.event.client_payload.env }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.8

      - name: Install packages
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Run build
        run: |
          if [ "${DEPLOY_ENV}" = "PROD" ]; then
            yarn gha:build:prod
          elif [ "${DEPLOY_ENV}" = "CANARY" ]; then
            yarn gha:build:canary
          else
            yarn gha:build:development
          fi
        working-directory: ./frontend

      - name: Deploy to FTP
        uses: ./.github/actions/deploy-ftp
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_user: ${{ secrets.FTP_USER }}
          ftp_pass: ${{ secrets.FTP_PASS }}
          remote_dir: ${{ secrets.FTP_FRONTEND_FOLDER }}
          local_dir: "./frontend/dist"
