name: FTP - Deploy SERVER

on:
  repository_dispatch:
    types:
      - deploy_be

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.client_payload.env }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: ./.github/actions/deploy-ftp
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_user: ${{ secrets.FTP_USER }}
          ftp_pass: ${{ secrets.FTP_PASS }}
          remote_dir: ${{ secrets.FTP_SERVER_FOLDER }}
          local_dir: "./server/src"
