name: FTP - Deploy FRONTEND

on:
  repository_dispatch:
    types:
      - deploy_fe

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.client_payload.env }}
    env:
      DEPLOY_ENV: ${{ github.event.client_payload.env }}
    steps:
      - name: Validate deploy source branch
        shell: bash
        run: |
          set -e

          REF="${GITHUB_REF#refs/heads/}"
          TARGET_ENV="${{ github.event.client_payload.env }}"

          if [[ ("$TARGET_ENV" == "PROD" || "$TARGET_ENV" == "CANARY") && "$REF" != release/* ]]; then
            echo "âŒ $TARGET_ENV deployments must run from release/* branches"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.target_branch }}

      - name: Install Volta
        run: |
          curl https://get.volta.sh | bash
          echo "$HOME/.volta/bin" >> $GITHUB_PATH

      - name: Install packages
        run: |
          volta install node yarn
          yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Run build
        run: |
          if [ "${DEPLOY_ENV}" = "PROD" ]; then
            yarn gha:build:prod
          elif [ "${DEPLOY_ENV}" = "CANARY" ]; then
            yarn gha:build:canary
          else
            yarn gha:build:development
          fi
        working-directory: ./frontend

      - name: Deploy to FTP
        uses: ./.github/actions/deploy-ftp
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_user: ${{ secrets.FTP_USER }}
          ftp_pass: ${{ secrets.FTP_PASS }}
          remote_dir: ${{ secrets.FTP_FRONTEND_FOLDER }}
          local_dir: "./frontend/dist"
